language: python
cache: pip

python:
    - "3.7"

env:
    global:
        # Doctr deploy key for madison-python/welcome
        - secure: "qsgkujAl1Q2SpG2lW1uixbtn9oEk50GgLyAt5mbhmXB3GTIRLeRPMeth5btLfcVU3N536ISP2AdsOprABVR54gITAn7xfoILjPA3WAmxvNQThSVpsTyGxog3ikW7JxD/sHgCKl3/9XvfKdAWFsgtGTSlHDcbtfFSFgGT0d2LLItgwXTpoSEQEEKq4Y6+OsPYfbQJjtrqSMP4SlQnQblJo/vcsyRPoo5zM9v9Uqbf3ZrbXJzl7kHtLMSrE5MDPcDjpOz39KlMHacuqv8K9VjW5J0Cs//CsI6U7BqmTRkV3MdJ1ZkBkNnygkST51t7R1uChVw6DsmeKJaEuyaQ8GD0yvAC/g2YCtB7vj97zN39+7jQw6LZ0Vn4FrD9y+OYRakvJOZkuuzPplmdpKtcynBkCmKgrjefbl5TuRbVmVvUOw2Ns0a6Ojc1xJZyJs4Zmf1KZzyjTBEk0VVwsKqiZMt3pXCFmDL/rxxDJvnQBKWv2BLp0I72eqyGRNISD/6oe3ycswKkrpBNMxoPT+Grfo+XpfbaXTCdYa3plG4hyi9o9fCeWdN2qdzy52Srtt7TCslFjPdznl+GnbBYhrBl0DrZJqzuefLfVNylPhpsallZsl10jr/nBLl5jvCYvGHXF5BmcGpjPRarBO60V4tiGzxAEWQeyUMbHPQakz5caS8zTmI="

install:
    - sudo apt-get update
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda env create --name madpy-welcome --file environment.yml
    - source activate madpy-welcome

script:
    - set -e
    - jupyter nbconvert welcome.ipynb --to slides
    - mv welcome.slides.html index.html
    - pip install doctr
    - doctr deploy . --built-docs .
