language: python
cache: pip

python:
    - "3.7"

install:
    - sudo apt-get update
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda env create --name madpy-welcome --file environment.yml
    - source activate madpy-welcome

script:
    - set -e
    - jupyter nbconvert welcome.ipynb --to slides
    - mv welcome.slides.html index.html
    - pip install doctr
    - doctr deploy --built-docs .
