[project]
name = "welcome"
version = "2025.1.3"
description = "Welcome slides for MadPy"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "cogapp",
  "jupyterlab",
  "nbconvert",
  "notebook",
]
