name: Publish to GitHub Pages

on:
  push:
    branches-ignore:
      - 'gh-pages' # excludes gh-pages

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Jupyter convert
        run: |
            ls -l
            pwd
            sudo apt update
            sudo apt install python3-venv pipx
            pipx ensurepath
            pipx install nbconvert
            pipx install cogapp
            jupyter-nbconvert welcome.ipynb --to slides
            mv welcome.slides.html index.html
            cog --check README.md

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
